### ISSUE TITLE
Regarding the texture issue

### ISSUE THREAD

**Issue by Q4st** [eArmada8/kuro_mdl_tool#2]
Your script supports model animation conversion to GLTF for Ys X, but textures do not. Please support texture extraction
Here are some samples
[test.zip](https://github.com/eArmada8/kuro_mdl_tool/files/12777205/test.zip)
thank you！

**Comment by Q4st** [comment]
Sorry, I understand, mdl does not contain textures, textures are in xtx format.
[b0000_00.zip](https://github.com/eArmada8/kuro_mdl_tool/files/12777264/b0000_00.zip)
![1](https://github.com/eArmada8/kuro_mdl_tool/assets/58507193/e7ad2ec0-b09a-4334-8ded-fbb65d2fdd1d)

**Comment by Q4st** [comment]
There are still some problems with UV
![1](https://github.com/eArmada8/kuro_mdl_tool/assets/58507193/dcb56961-59bb-42ae-bbef-3318fadc3f20)

**Comment by eArmada8** [comment]
Hi,

My tool is for meshes and animations only, it does not do anything for textures because textures are not in the MDL.  For Switch games, please use this: https://github.com/KillzXGaming/Switch-Toolbox/releases

The UVs are correct.  They are using texture coordinate wrapping / mirroring.  I will eventually update the wiki for Kuro, but for now you can reference the same tutorial for Cold Steel here:  https://github.com/eArmada8/ed8pkg2gltf/wiki/Modifying-materials-(textures-and-shaders)#texture-coordinate-wrapping-mirroring-and-other-nonsense

I am closing this issue since it is not an issue with my tool.
