### ISSUE TITLE
[Request] Ys X: Nordics Model Injection

### ISSUE THREAD

**Issue by zelgodis** [eArmada8/kuro_mdl_tool#3]
Requesting model injection for Ys X: Nordics, as it shares the same engine as Kuro 1 and 2

**Comment by eArmada8** [comment]
I added basic support in v1.5.1.  If it works, great.  If it doesn't, it will have to wait until there is a PC English language release.

In the meantime, you are welcome to fork the repository and add support.  I will not be able to evaluate any pull requests, however, since the game is not available in my region or on my platform (Windows) so I cannot test.
